### ISSUE TITLE
#include <moveit/move_group_interface/move_group_interface.h>

### ISSUE THREAD

**Issue by pibaopi** [zfshenGit/ur_control#1]
老哥，我在编译的时候发现这一个头文件#include <moveit/move_group_interface/move_group_interface.h>无法找到，以及源码中的  moveit::planning_interface::MoveGroupInterface group("manipulator"); 这一语句也提示报错 ，是否缺少了moveit包呢?

**Comment by zfshenGit** [comment]
是的，缺少相应的move_group_interface.h接口文件，这个是在ros的moveit包里的，安装ros的时候一般都是装好的，具体路径为/opt/ros/melodic/include/moveit/move_group_interface/move_group_interface.h，如果你没装moveit包的装一下应该就行了

**Comment by pibaopi** [comment]
好的，谢谢。我刚刚找了一下，发现在你给的路径中有所需要的文件，但是我不懂得怎么去用它，是将这个#include <moveit/move_group_interface/move_group_interface.h>路径改成#include </opt/ros/melodic/include/moveit/move_group_interface/move_group_interface.h>这样就可以了吗

**Comment by zfshenGit** [comment]
如果说我给的路径里有这个文件的话，include的话按理说应该是不会出错的，因为它会直接在opt/ros/melodic/include路径下去找.h文件，所以写成#include <moveit/move_group_interface/move_group_interface.h>这样是没问题的，前提是我给的路径里有这个文件。改成#include </opt/ros/melodic/include/moveit/move_group_interface/move_group_interface.h>这样我没试过，不知道可不可以，你可以试一试

**Comment by pibaopi** [comment]
非常感谢您的回复，我将您的工程包中的marm_palaning部分拿过来单独进行了编译，能够编译成功，但是在我启动ur后运行rosrun marm_planning test_custom_node这一语句给我提示报错了，像这样
![微信图片_20211011151122](https://user-images.githubusercontent.com/77523889/136747470-b10ac56c-0abc-4a83-bbd6-7fe0fe7c2d39.png)
然后后面我不知道怎么处理了，你能帮我看看嘛，非常感谢！

**Comment by zfshenGit** [comment]
你好，关于图片中的错误，我在执行的时候是没问题的，我也不知道你为什么会出现这个错误，根据我自己的了解，可能是启动ur5之后没有启动moveit，所以找不到group 'manipulator'；另外，你也可以试一下执行moveit_ik_demo.py程序，这个python程序和test_custom.cpp程序功能是一样的，都可以实现在操作空间控制ur5（即给定期望的ur5末端执行器的位置和姿态，控制ur5从初始位置运动到期望的目标位置），看看python程序是不是也会出现同样的错误？

**Comment by pibaopi** [comment]
好的，真的非常谢谢您的解答，我这边刚才尝试了一下发现确实向您所说的那样没有启动moveit，在启动moveit过后再启动这个节点发现机械臂可以进行运动了，其他的代码我再去看看。我有一个问题想要问您，您这个marm_planning包里的这些程序主要是用来实现什么功能的呢？再次感谢您的解答！

**Comment by zfshenGit** [comment]
关于marm_planning包里的程序所实现的功能你可以参考B站的一个教学视频，这个视频是古月居的一个关于moveit的教程，我上传的marm_planning包里的代码来源于这个视频教程，但是所用的机器人模型和视频中不同，所以做了相应地修改。网址为：https://www.bilibili.com/video/BV1EA411K7Jy?from=search&seid=3673290674376604326&spm_id_from=333.337.0.0

**Comment by pibaopi** [comment]
好的，非常感谢！！！！！！！！！！！
